services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - trainer-service
      - predictor-service
    networks:
      - ml-net
    restart: on-failure

  trainer-service:
    build: ./trainer-service
    container_name: trainer-service
    ports:
      - "9001:9000"
    volumes:
      - ./models:/app/models
    networks:
      - ml-net
    restart: on-failure

  predictor-service:
    build: ./predictor-service
    container_name: predictor-service
    ports:
      - "9002:9000"
    volumes:
      - ./models:/app/models
    networks:
      - ml-net
    restart: on-failure
      
  redis:
    image: redis:8.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ml-net
    restart: on-failure
    
networks:
  ml-net:
    driver: bridge